wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721761927
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.17.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
in_channels:
  desc: null
  value: 4
num_channels:
  desc: null
  value:
  - 20
  - 20
  - 20
  - 20
kernel_size:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.004598
batch_size:
  desc: null
  value: 152
hp_search:
  desc: null
  value: true
input_size:
  desc: null
  value: 72
horizon:
  desc: null
  value: 1
batch_size_dl:
  desc: null
  value: 128
