wandb_version: 1

features:
  desc: null
  value:
  - timestamp
  - Weather_Temperature_Celsius
  - Weather_Relative_Humidity
  - Global_Horizontal_Radiation
  - Active_Power
label:
  desc: null
  value: Active_Power
input_size:
  desc: null
  value: 36
horizon:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 152
cv_iter:
  desc: null
  value:
  - 0.5
  - 0.7
  - 0.9
train_dataset_size:
  desc: null
  value: 0.6
val_dataset_size:
  desc: null
  value: 0.2
test_dataset_size:
  desc: null
  value: 0.2
num_channels:
  desc: null
  value:
  - 20
  - 20
  - 20
  - 20
in_channels:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.004598
train:
  desc: null
  value: false
test:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721761652
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 7
      - 16
      - 23
      - 66
      4: 3.10.14
      5: 0.17.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
